# Generated by Django 5.2.6 on 2025-09-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_remove_project_technology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documentation_link',
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_file',
            field=models.FileField(blank=True, upload_to='project_documentation/'),
        ),
    ]
