# Generated by Django 5.2.6 on 2025-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_documentation_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='project_image',
        ),
        migrations.AddField(
            model_name='project',
            name='index_image',
            field=models.FileField(blank=True, upload_to='index_images/'),
        ),
    ]
