# Generated by Django 5.2.6 on 2025-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_image_project_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='powerbi_iframe_url',
            field=models.URLField(blank=True),
        ),
    ]
