# Generated by Django 5.2.6 on 2025-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_powerbi_iframe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='powerbi_description',
            field=models.TextField(blank=True),
        ),
    ]
